name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        config:
          - {os: macos-latest, compiler: clang++}
          - {os: windows-latest, compiler: g++}

    
    runs-on: ${{ matrix.config.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set compiler
      run: |
        echo "CC=${{ matrix.config.compiler }}" >> $GITHUB_ENV
        echo "CXX=${{ matrix.config.compiler }}" >> $GITHUB_ENV

    - name: Setup MinGW (only for windows with g++)
      if: ${{ matrix.config.os == 'windows-latest' && matrix.cnfig.compiler == 'g++' }}
      run: |
        choco install mingw
        echo "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin" >> $GITHUB_PATH

    - name: Configure and build main application
      shell: bash
      run: |
        cd src
        mkdir -p build
        cd build
        if [ "${{ matrix.config.os }}" == "windows-latest" ] && [ "${{ matrix.config.compiler }}" == "g++" ]; then
          cmake .. -G "MinGW Makefiles" -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++
          mingw32-make
        else
          cmake ..
          make
        fi



    - name: Setup Google Test
      run: |
        if [ ! -d "googletest" ]; then
          git clone https://github.com/google/googletest.git
        fi
        cd googletest
        cd googletest
        mkdir -p build
        cd build
        cmake ../..
        make

    - name: Run Tests
      run: |
        cd googletest/build
        ./validInputTests
        # Uncomment below if you want to also run invalidInputTests
        # ./invalidInputTests
