name: Cppcheck

on:
  push:
    paths:
    - '**.cpp'
    - '**.h'
  pull_request:
    paths:
    - '**.cpp'
    - '**.h'

jobs:
  static-analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Cppcheck
      run: sudo apt-get install -y cppcheck

    - name: Run Cppcheck for src/ with C++11 standard
      run: |
        cppcheck --enable=all --std=c++11 src/ > src_cppcheck.txt 2>&1
        
    - name: Run Cppcheck for tests/ with C++17 standard
      run: |
        cppcheck --enable=all --std=c++17 tests/ > tests_cppcheck.txt 2>&1

    - name: Fail if issues were found
      run: |
        if grep -q "(error)" src_cppcheck.txt || grep -q "(error)" tests_cppcheck.txt; then
          echo "Cppcheck found errors"
          exit 1
        fi
