name: Cppcheck

on:
  push:
    paths:
    - 'src/**.cpp'
    - 'src/**.h'
    - 'tests/**.cpp'
    - 'tests/**.h'
  pull_request:
    paths:
    - 'src/**.cpp'
    - 'src/**.h'
    - 'tests/**.cpp'
    - 'tests/**.h'

jobs:
  check:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Cppcheck
      run: |
        choco install cppcheck

    - name: Run Cppcheck (src/ with C++11 standard)
      run: |
        cppcheck --enable=all --error-exitcode=1 --suppress=missingIncludeSystem --std=c++11 src/

    - name: Run Cppcheck (tests/ with C++17 standard)
      run: |
        cppcheck --enable=all --error-exitcode=1 --suppress=missingIncludeSystem --std=c++17 tests/
